<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Security Headers & Rate Limiting Helper
 * 
 * Architecture Note:
 * This helper acts as the equivalent of Helmet.js in the Node/Express ecosystem. 
 * By loading this in the MY_Controller constructor, we mathematically guarantee 
 * that every single HTTP response generated by the platform is fortified against 
 * common web vulnerabilities (XSS, Clickjacking, MIME sniffing).
 */

// ── HTTP SECURITY HEADERS & CORS ──────────────────────────────

if ( ! function_exists('set_security_headers'))
{
    /**
     * Master Security Header Injector
     * Logic Explanation:
     * Injects strict security policies directly into the HTTP response. It also 
     * dynamically handles Cross-Origin Resource Sharing (CORS) to allow the external 
     * AR Client to communicate with this backend securely.
     */
    function set_security_headers()
    {
        // 1. Prevent browsers from guessing the MIME type, stopping drive-by download attacks
        header('X-Content-Type-Options: nosniff');

        // 2. Prevent the platform from being loaded in a malicious iframe (Clickjacking defense)
        header('X-Frame-Options: DENY');

        // 3. Force the browser's built-in Cross-Site Scripting (XSS) filter into block mode
        header('X-XSS-Protection: 1; mode=block');

        // 4. Privacy: Strip referrer info when navigating to external sites
        header('Referrer-Policy: strict-origin-when-cross-origin');

        // 5. Content Security Policy (CSP) Algorithm
        // Security: This is the ultimate defense against XSS. It strictly whitelists 
        // where scripts and styles can be loaded from. We allow 'self' and the specific 
        // Cloudflare CDN required to render our Swagger API Docs.
        header(
            "Content-Security-Policy: " .
            "default-src 'self'; " .
            "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; " .
            "style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; " .
            "img-src 'self' data: https:; " .
            "connect-src 'self'; " .
            "frame-ancestors 'none';"
        );

        // 6. Disable hardware APIs to reduce the platform's attack surface
        header("Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()");

        // 7. Environment-Aware Strict Transport Security (HSTS)
        // Forces browsers to ONLY use HTTPS, but smartly disables itself on localhost 
        // to prevent local development environments from breaking.
        if (defined('ENVIRONMENT') && ENVIRONMENT === 'production') {
            header('Strict-Transport-Security: max-age=31536000; includeSubDomains');
        }

        // 8. Security through Obscurity: Hide the backend tech stack from attackers
        header_remove('X-Powered-By');
        header_remove('Server');

        // ── CORS (Cross-Origin Resource Sharing) ALGORITHM ─────────────────
        
        // Define a strict whitelist of allowed external clients (e.g., the AR App)
        $allowed = [
            'http://localhost',
            'http://localhost:3000',
            'http://localhost:8080',
            'http://127.0.0.1',
        ];

        $origin = $_SERVER['HTTP_ORIGIN'] ?? '';

        // Conditional Origin Echo: If the request comes from a whitelisted origin, 
        // we echo that specific origin back. This is far more secure than using the wildcard '*'.
        if (in_array($origin, $allowed, TRUE)) {
            header('Access-Control-Allow-Origin: ' . $origin);
            header('Access-Control-Allow-Credentials: true'); // Required for session cookies
        } elseif (defined('ENVIRONMENT') && ENVIRONMENT !== 'production') {
            // Fallback for rapid local development
            header('Access-Control-Allow-Origin: *');
        }

        // Define permitted HTTP Methods and Headers for external clients
        header('Access-Control-Allow-Methods: GET, POST, DELETE, OPTIONS');
        header('Access-Control-Allow-Headers: Content-Type, Authorization, X-API-Key');
        
        // Cache the preflight response for 1 hour to reduce server load
        header('Access-Control-Max-Age: 3600');

        // CORS Preflight Interceptor
        // Complex Logic: When a frontend client sends a JSON POST request, the browser 
        // automatically sends a preliminary OPTIONS request first to check permissions. 
        // We catch that here, return a 204 No Content, and exit immediately to prevent 
        // the CodeIgniter router from processing an empty payload.
        if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
            http_response_code(204);
            exit();
        }
    }
}

// ── RATE LIMITING ALGORITHMS ──────────────────────────────────

if ( ! function_exists('check_rate_limit'))
{
    /**
     * Session-Based Fixed Window Rate Limiter
     * Algorithm Explanation:
     * This protects sensitive endpoints (like /auth/login) from brute-force attacks.
     * It stores a 'start' timestamp and a 'hits' counter in the user's session.
     * If the hits exceed the maximum allowed within the defined time window, it trips the breaker.
     *
     * @param  string $key            The unique identifier for this limit (e.g., 'login')
     * @param  int    $max_hits       Maximum allowed requests
     * @param  int    $window_seconds Timeframe in seconds before the counter resets
     * @return bool                   TRUE if allowed, FALSE if rate limit exceeded
     */
    function check_rate_limit($key, $max_hits, $window_seconds)
    {
        $CI   =& get_instance();
        $data = $CI->session->userdata('rl_' . $key);
        $now  = time();

        // Condition A: Start a fresh tracking window if none exists or the previous one expired
        if ( ! $data || ($now - $data['start']) > $window_seconds) {
            $CI->session->set_userdata('rl_' . $key, ['hits' => 1, 'start' => $now]);
            return TRUE;
        }

        // Condition B: The user has exceeded the maximum hits within the active window
        if ($data['hits'] >= $max_hits) {
            return FALSE; 
        }

        // Condition C: Within the window and under the limit, increment the counter
        $CI->session->set_userdata('rl_' . $key, [
            'hits'  => $data['hits'] + 1,
            'start' => $data['start'],
        ]);
        
        return TRUE;
    }
}

if ( ! function_exists('rate_limit_response'))
{
    /**
     * Standardized HTTP 429 Generator
     * Logic:
     * Halts execution and returns the industry-standard HTTP 429 (Too Many Requests) status.
     * Critically, it injects the 'Retry-After' header, which tells automated clients 
     * exactly how many seconds to wait before trying again.
     */
    function rate_limit_response($retry_after = 900)
    {
        http_response_code(429);
        header('Content-Type: application/json');
        header('Retry-After: ' . $retry_after); // Tell the client when the timeout expires
        
        echo json_encode([
            'status'  => 429,
            'message' => 'Too many requests. Please try again in ' . ($retry_after / 60) . ' minutes.',
        ]);
        
        exit(); // Halt CodeIgniter execution
    }
}